# Generated by Django 4.2.1 on 2023-06-12 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_vehicles_vehicle_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('vehicles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.vehicles')),
            ],
        ),
    ]
