# Generated by Django 4.2.1 on 2023-06-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_display'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='display',
            name='status',
        ),
        migrations.AddField(
            model_name='vehicles',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
