# Generated by Django 4.2.2 on 2023-06-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='numberPlate',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='vehicleType',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
