# Generated by Django 4.2.2 on 2023-06-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_vehicles_created_alter_vehicles_numberplate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
