# Generated by Django 4.2.2 on 2023-06-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_messages_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Available', 'Available')], max_length=200, null=True),
        ),
    ]
