# Generated by Django 4.2.1 on 2023-06-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_vehicles_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
